_format_version: "3.0"

services:
  # Registry Service
  - name: registry-service
    url: http://registry-service:3001
    routes:
      - name: registry-route
        paths:
          - /api/registry
          - /api/customers
          - /api/companies
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      # JWT verification - verifies token validity
      - name: jwt
        config:
          claims_to_verify:
            - exp
            - iat
      # OIDC plugin for OAuth2/OIDC flow (uncomment when OIDC provider is ready)
      # - name: oidc
      #   config:
      #     issuer: ${KONG_OIDC_ISSUER:-https://auth.collector.local/realms/collector}
      #     client_id: ${KONG_OIDC_CLIENT_ID:-collector-api}
      #     client_secret: ${KONG_OIDC_CLIENT_SECRET}
      #     bearer_only: "yes"
      #     verify_parameters: "yes"
      #     discovery: https://auth.collector.local/realms/collector/.well-known/openid-configuration
      #     introspection_endpoint: https://auth.collector.local/realms/collector/protocol/openid-connect/token/introspect
      #     introspection_endpoint_auth_method: client_secret_post
      #     consumer_claim: email
      #     consumer_by: username
      #     scope: openid profile email
      #     sessions_secret: ${KONG_OIDC_SESSIONS_SECRET}
      #     redirect_uri: ${KONG_OIDC_REDIRECT_URI:-http://localhost:8000/}
      #     logout_path: /logout
      #     logout_redirect_uri: ${KONG_OIDC_LOGOUT_REDIRECT_URI:-http://localhost:8000/}
      # Request transformer to inject identity headers from verified JWT/OIDC token
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Forwarded-For:$(trusted_ip)"
              # Extract from JWT consumer (when using JWT plugin)
              - "X-User-Id:$(consumer.id)"
              - "X-User-Username:$(consumer.username)"
              # Extract from OIDC token claims (when using OIDC plugin)
              # These use Nginx variables populated by oidc plugin
              - "X-User-Id:$(x_userinfo_sub)"
              - "X-User-Email:$(x_userinfo_email)"
              - "X-Tenant-Id:$(x_userinfo_tenant_id)"
              - "X-User-Roles:$(x_userinfo_realm_access_roles)"
              - "X-User-Scopes:$(x_userinfo_scope)"
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Authorization
            - x-tenant-id
            - X-User-Id
            - X-User-Email
            - X-Tenant-Id
            - X-User-Roles
            - X-User-Scopes
      - name: correlation-id
        config:
          header_name: X-Request-ID
          echo_downstream: true

  # Invoices Service
  - name: invoices-service
    url: http://invoices-service:3002
    routes:
      - name: invoices-route
        paths:
          - /api/invoices
          - /api/payments
          - /api/dunnings
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: jwt
        config:
          claims_to_verify:
            - exp
            - iat
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(consumer.id)"
              - "X-User-Username:$(consumer.username)"
              - "X-User-Id:$(x_userinfo_sub)"
              - "X-User-Email:$(x_userinfo_email)"
              - "X-Tenant-Id:$(x_userinfo_tenant_id)"
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - X-User-Id
            - X-Tenant-Id
            - X-User-Email
            - X-User-Roles
      - name: correlation-id
        config:
          header_name: X-Request-ID
          echo_downstream: true

  # Orders Service
  - name: orders-service
    url: http://orders-service:3003
    routes:
      - name: orders-route
        paths:
          - /api/orders
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: jwt
        config:
          claims_to_verify:
            - exp
            - iat
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(consumer.id)"
              - "X-User-Username:$(consumer.username)"
              - "X-User-Id:$(x_userinfo_sub)"
              - "X-User-Email:$(x_userinfo_email)"
              - "X-Tenant-Id:$(x_userinfo_tenant_id)"
      - name: cors
      - name: correlation-id

  # Delivery Service
  - name: delivery-service
    url: http://delivery-service:3004
    routes:
      - name: delivery-route
        paths:
          - /api/delivery
          - /api/delivery-notes
          - /api/carriers
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: jwt
        config:
          claims_to_verify:
            - exp
            - iat
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(consumer.id)"
              - "X-User-Username:$(consumer.username)"
              - "X-User-Id:$(x_userinfo_sub)"
              - "X-User-Email:$(x_userinfo_email)"
              - "X-Tenant-Id:$(x_userinfo_tenant_id)"
      - name: cors
      - name: correlation-id

  # Offers Service
  - name: offers-service
    url: http://offers-service:3005
    routes:
      - name: offers-route
        paths:
          - /api/offers
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: jwt
        config:
          claims_to_verify:
            - exp
            - iat
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(consumer.id)"
              - "X-User-Username:$(consumer.username)"
              - "X-User-Id:$(x_userinfo_sub)"
              - "X-User-Email:$(x_userinfo_email)"
              - "X-Tenant-Id:$(x_userinfo_tenant_id)"
      - name: cors
      - name: correlation-id

# Global plugins (applied to all services)
plugins:
  - name: request-transformer
    config:
      add:
        headers:
          - "X-Forwarded-For:$(trusted_ip)"
  - name: correlation-id
    config:
      header_name: X-Request-ID
      echo_downstream: true
