apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-service
  namespace: collector-platform
  labels:
    app: registry-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-service
  namespace: collector-platform
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-service
  namespace: collector-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-service
subjects:
- kind: ServiceAccount
  name: registry-service
  namespace: collector-platform

